query {
  content {
    title
    logo
    bannerImages
    metaDescription
    metaFavicon
    metaKeyWords
    sections
    infoImage
    description
    contact
    footer
    updatedAt
    createdAt
  }
}