query {
  content {
    title
    code
    logo
    metaDescription
    metaFavicon
    metaKeyWords
    sections
    infoImage
    description
    contact
    footer
    updatedAt
    createdAt
  }
}