mutation($email: String!, $password: String!) {
  login(email: $email, password:  $password) {
    token
    user {
      firstName
      id
      email
      role
      cart {
        id
        products {
          quantity
          product {
            id
            name
            price
            image
            slug
          }
        }
      }
    }
  }
}