query($category: String $subCategory: String) {
  products(category: $category subCategory: $subCategory) {
    id
    slug
    name
    image
    category {
      id
      name
      slug
    }
    subCategories {
      id
      name
      slug
    }
    variants {
      id
      name
    }
  }
}