query($id: String) {
  product(id: $id) {
    id
    slug
    name
    image
    price
    description
    stockQuantity
    category {
      id
      name
      slug
    }
    subCategories {
      id
      name
      slug
    }
    variants {
      id
      name
    }
  }
}