mutation($email: String!, $password: String!) {
  signup(email: $email, password:  $password) {
    token
    user {
      firstName
      id
      email
      role
      image
      cart {
        id
        products {
          quantity
          product {
            id
            name
            price
            image
            slug
          }
        }
      }
    }
  }
}