mutation($input: CartInput!) {
  updateCartItem(input: $input) {
    id
    products {
      id
      quantity
      product {
        id
        name
        price
        image
        slug
      }
    }
  }
}