query {
  user {
    email
    image
    id
    role
    cart {
      id
      products {
        quantity
        product {
          id
          name
          price
          image
          slug
        }
      }
    }
  }
}