query {
  user {
    email
    image
    id
    role
    firstName
    lastName
    addresses {
      id
      type
      street
      number
      complement
      zip
      district
      city
      state
      country
      firstName
      lastName
    }
    cart {
      id
      products {
        quantity
        product {
          id
          name
          price
          image
          slug
        }
      }
    }
  }
}